# Generated by Django 6.0.2 on 2026-02-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_address_order_city_order_full_name_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True, verbose_name='المحافظة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشحن')),
            ],
            options={
                'verbose_name': 'سعر شحن',
                'verbose_name_plural': 'أسعار الشحن',
            },
        ),
    ]
