# Generated by Django 6.0.2 on 2026-03-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_shippingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/instapay/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('visa', 'Visa'), ('cash', 'Cash'), ('INSTAPAY', 'InstaPay')], default='visa', max_length=20),
        ),
    ]
