# Generated by Django 6.0.2 on 2026-02-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_hex',
            field=models.CharField(default='000080#', max_length=7),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(default='Navy Blue', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_variants', to='products.product'),
        ),
    ]
