# Generated by Django 6.0.3 on 2026-06-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_section_alter_category_name_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='نسبة الخصم بالـ % (0 = مفيش خصم، 15 = خصم 15%)'),
        ),
    ]
