# Generated by Django 6.0.3 on 2026-06-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='النص اللي هيظهر في الشريط الإعلاني', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='فعّل أو عطّل الشريط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement Bar',
                'verbose_name_plural': 'Announcement Bars',
            },
        ),
    ]
