# Generated by Django 6.0.2 on 2026-02-06 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_price_alter_cartitem_variant'),
        ('products', '0002_size_remove_product_stock_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant'),
        ),
    ]
